version: '3'
services:
  db:

    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

volumes:
  mysql-data: